apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-app
  namespace: gitops-demo
spec:
  selector:
    app: gitops-demo-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP


  
